version: '3.9'

services:
  django_together:
    volumes:
      - static:/app/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/app/static
    depends_on:
      - django_together

volumes:
  static: